version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./harvester_results:/output
      - db_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DB_PATH=/data/scans.db

volumes:
  db_data: